[package]
name = "yao-gc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "3.2.1"
peg = "0.8.0"
subtle = "2.4.1"
